#!/bin/bash
# Script Name: alsd3.sh
# ID: SCR-ID-20260412153017-UT4CBBXUU6
# Assigned with:
# Created by: Tyler Jensen
# Email: tylerjensen5@yahoo.com
# Alias Call: alsd3

# actd - Active Directory Alias Manager with custom paths + list option

CONFIG_DIR="/mnt/c/scr/bash/alsd/logs"
CONFIG_FILE="$CONFIG_DIR/aliases.csv"
ALIAS_DIR="/mnt/c/scr/aliases/lib/act"
ALIAS_FILE="$ALIAS_DIR/alsdirc"

usage() {
    echo "Usage:"
    echo "  actd -a <alias_name> <directory> [-L]   Add new alias"
    echo "  actd -e <alias_name> <directory> [-L]   Edit existing alias"
    echo "  actd -d <alias_name>                    Delete alias"
    echo "  actd -l                                 List all aliases"
    exit 1
}

mkdir -p "$CONFIG_DIR"
mkdir -p "$ALIAS_DIR"
touch "$CONFIG_FILE"

# Rebuild alias file from CSV
rebuild_alias_file() {
    echo "# Generated by actd" > "$ALIAS_FILE"
    while IFS=, read -r name dir extra; do
        [ -n "$name" ] && [ -n "$dir" ] && {
            if [ "$extra" = "L" ]; then
                echo "alias $name='cd $dir && ll -ah'" >> "$ALIAS_FILE"
            else
                echo "alias $name='cd $dir'" >> "$ALIAS_FILE"
            fi
        }
    done < "$CONFIG_FILE"
}

add_alias() {
    local name=$1
    local dir=$2
    local opt=$3
    if grep -q "^$name," "$CONFIG_FILE"; then
        echo "Alias '$name' already exists. Use -e to edit."
        exit 1
    fi
    if [ "$opt" = "-L" ]; then
        echo "$name,$dir,L" >> "$CONFIG_FILE"
    else
        echo "$name,$dir" >> "$CONFIG_FILE"
    fi
    rebuild_alias_file
    echo "Added alias: $name -> $dir ${opt:+(+ ll -ah)}"
}

edit_alias() {
    local name=$1
    local dir=$2
    local opt=$3
    if ! grep -q "^$name," "$CONFIG_FILE"; then
        echo "Alias '$name' does not exist. Use -a to add."
        exit 1
    fi
    if [ "$opt" = "-L" ]; then
        sed -i "s|^$name,.*|$name,$dir,L|" "$CONFIG_FILE"
    else
        sed -i "s|^$name,.*|$name,$dir|" "$CONFIG_FILE"
    fi
    rebuild_alias_file
    echo "Updated alias: $name -> $dir ${opt:+(+ ll -ah)}"
}

delete_alias() {
    local name=$1
    if ! grep -q "^$name," "$CONFIG_FILE"; then
        echo "Alias '$name' does not exist."
        exit 1
    fi
    sed -i "/^$name,/d" "$CONFIG_FILE"
    rebuild_alias_file
    echo "Deleted alias: $name"
}

list_aliases() {
    echo "Current directory aliases:"
    if [ -s "$CONFIG_FILE" ]; then
        column -t -s, "$CONFIG_FILE"
    else
        echo "None yet."
    fi
}

case "$1" in
    -a) [ $# -ge 3 ] || usage; add_alias "$2" "$3" "$4" ;;
    -e) [ $# -ge 3 ] || usage; edit_alias "$2" "$3" "$4" ;;
    -d) [ $# -eq 2 ] || usage; delete_alias "$2" ;;
    -l) list_aliases ;;
    *) usage ;;
esac
