#!/bin/bash
# Script Name: alsd6.sh
# ID: SCR-ID-20260412153039-UJFDFLF1WE
# Assigned with:
# Created by: Tyler Jensen
# Email: tylerjensen5@yahoo.com
# Alias Call: alsd6

# alsd - Active Directory Alias Manager
# Default config CSV and generated alias file

# Default paths (can be overridden with -c / -f)
CONFIG_DIR="/mnt/c/scr/bash/alsd/logs"
CONFIG_FILE="$CONFIG_DIR/aliases.csv"
ALIAS_DIR="/mnt/c/scr/aliases/lib/act"
ALIAS_FILE="$ALIAS_DIR/alsdirc"

usage() {
    echo "alsd - Active Directory Alias Manager"
    echo
    echo "Usage:"
    echo "  alsd -a <alias_name> <directory> [-L]   Add new alias (ll -ah if -L)"
    echo "  alsd -e <alias_name> <directory> [-L]   Edit existing alias"
    echo "  alsd -d <alias_name>                     Delete alias"
    echo "  alsd -l                                  List all aliases"
    echo "  alsd -r                                  Restore aliases from CSV to alias file"
    echo "  alsd -c <path>                           Change default config directory"
    echo "  alsd -f <path>                           Change default alias file"
    echo "  alsd -h                                  Show this help and examples"
    echo
    echo "Examples:"
    echo "  alsd -a a0 /mnt/c/scr -L               # Add a0 alias with ll -ah"
    echo "  alsd -e -L a0 /mnt/c/newdir             # Edit a0 to new directory with ll -ah"
    echo "  alsd -d a0                              # Delete alias a0"
    echo "  alsd -l                                 # List all aliases"
    echo "  alsd -r                                 # Restore alias file from CSV"
    exit 0
}

mkdir -p "$CONFIG_DIR"
mkdir -p "$ALIAS_DIR"
touch "$CONFIG_FILE"

# Rebuild alias file from CSV
rebuild_alias_file() {
    echo "# Generated by alsd" > "$ALIAS_FILE"
    while IFS=, read -r name dir extra; do
        [ -n "$name" ] && [ -n "$dir" ] && {
            if [ "$extra" = "L" ]; then
                echo "alias $name='cd $dir && ll -ah'" >> "$ALIAS_FILE"
            else
                echo "alias $name='cd $dir'" >> "$ALIAS_FILE"
            fi
        }
    done < "$CONFIG_FILE"
}

add_alias() {
    local name="" dir="" list_flag=""
    for arg in "$@"; do
        if [ "$arg" = "-L" ]; then list_flag="L"
        elif [ -z "$name" ]; then name="$arg"
        elif [ -z "$dir" ]; then dir="$arg"
        fi
    done
    [ -z "$name" ] || [ -z "$dir" ] && { echo "Usage: alsd -a <alias_name> <directory> [-L]"; exit 1; }
    grep -q "^$name," "$CONFIG_FILE" && { echo "Alias '$name' exists. Use -e to edit."; exit 1; }
    echo "$name,$dir${list_flag:+,L}" >> "$CONFIG_FILE"
    rebuild_alias_file
    echo "Added alias: $name -> $dir ${list_flag:+(+ ll -ah)}"
}

edit_alias() {
    local name="" dir="" list_flag=""
    for arg in "$@"; do
        if [ "$arg" = "-L" ]; then list_flag="L"
        elif [ -z "$name" ]; then name="$arg"
        elif [ -z "$dir" ]; then dir="$arg"
        fi
    done
    [ -z "$name" ] || [ -z "$dir" ] && { echo "Usage: alsd -e <alias_name> <directory> [-L]"; exit 1; }
    grep -q "^$name," "$CONFIG_FILE" || { echo "Alias '$name' does not exist."; exit 1; }
    if [ "$list_flag" = "L" ]; then
        sed -i "s|^$name,.*|$name,$dir,L|" "$CONFIG_FILE"
    else
        sed -i "s|^$name,.*|$name,$dir|" "$CONFIG_FILE"
    fi
    rebuild_alias_file
    echo "Updated alias: $name -> $dir ${list_flag:+(+ ll -ah)}"
}

delete_alias() {
    local name="$1"
    grep -q "^$name," "$CONFIG_FILE" || { echo "Alias '$name' does not exist."; exit 1; }
    sed -i "/^$name,/d" "$CONFIG_FILE"
    rebuild_alias_file
    echo "Deleted alias: $name"
}

list_aliases() {
    echo "Current directory aliases:"
    [ -s "$CONFIG_FILE" ] || { echo "None yet."; return; }
    printf "%-10s %-50s %-5s\n" "ALIAS" "DIRECTORY" "LL"
    printf "%-10s %-50s %-5s\n" "-----" "---------" "--"
    while IFS=, read -r name dir extra; do
        printf "%-10s %-50s %-5s\n" "$name" "$dir" "${extra:++L}"
    done < "$CONFIG_FILE"
}

restore_aliases() {
    rebuild_alias_file
    echo "Alias file restored from CSV."
}

# Main argument parsing
case "$1" in
    -a) shift; [ $# -ge 2 ] || usage; add_alias "$@" ;;
    -e) shift; [ $# -ge 2 ] || usage; edit_alias "$@" ;;
    -d) [ $# -eq 2 ] || usage; delete_alias "$2" ;;
    -l) list_aliases ;;
    -r) restore_aliases ;;
    -c) [ $# -eq 2 ] || usage; CONFIG_DIR="$2"; CONFIG_FILE="$CONFIG_DIR/aliases.csv"; mkdir -p "$CONFIG_DIR"; touch "$CONFIG_FILE"; echo "Config dir set to $CONFIG_DIR" ;;
    -f) [ $# -eq 2 ] || usage; ALIAS_FILE="$2"; ALIAS_DIR=$(dirname "$ALIAS_FILE"); mkdir -p "$ALIAS_DIR"; touch "$ALIAS_FILE"; echo "Alias file set to $ALIAS_FILE" ;;
    -h|--help) usage ;;
    *) usage ;;
esac
