#!/usr/bin/env bash
# Script Name: i_gems.sh
# ID: SCR-ID-20260329042917-3SQR59AT6M
# Assigned with:
# Created by: Tyler Jensen
# Email: tylerjensen5@yahoo.com
# Alias Call: i_gems
#sudo apt install pv
gem install tty
gem install pastel
gem install progressbar
gem install tty-prompt pastel
gem install optimist
gem install prawn
gem install pdfkit
gem install gtk3
gem install gtk4
gem install bundler
gem install activerecord
gem install ansible
gem install bcrypt
gem install bcrypt
gem install openssl
gem install jwt
gem install rbnacl
gem install bundler
gem install byebug
gem install capistrano
gem install ansible
gem install chef
gem install chef
gem install colorize
gem install bundler
gem install csv
gem install daru
gem install dotenv
gem install engtagger
gem install faraday
gem install grape
gem install hanami
gem install hanami
gem install roda
gem install grape
gem install jbuilder
gem install rails-api
gem install highline
gem install httparty
gem install httparty
gem install rest-client
gem install faraday
gem install sinatra
gem install ruby-progressbar
gem install jbuilder
gem install json
gem install jwt
gem install lolize
gem install mechanize
gem install minitest
gem install mxnet
gem install nokogiri
gem install mechanize
gem install selenium-webdriver
gem install watir
gem install optparse
gem install pg
gem install pragmatic_segmenter
gem install pry
gem install rails
gem install dotenv
gem install rspec
gem install minitest
gem install byebug
gem install simplecov
gem install rails
gem install rails-api
gem install rails-assets
gem install rainbow
gem install rake
gem install rbnacl
gem install rest-client
gem install roda
gem install roo
gem install rspec
gem install ruby-dnn
gem install ruby-dnn
gem install tensorflow
gem install sciruby
gem install mxnet
gem install ruby-progressbar
gem install rubyXL
gem install rubyXL
gem install roo
gem install daru
gem install smarter_csv
gem install rufus-scheduler
gem install sciruby
gem install selenium-webdriver
gem install sequel
gem install simplecov
gem install sinatra
gem install smarter_csv
gem install sqlite3
gem install stemmer
gem install tensorflow
gem install text
gem install text
gem install pragmatic_segmenter
gem install engtagger
gem install stemmer
gem install thor
gem install thor
gem install trollop
gem install highline
gem install rainbow
gem install watir
gem install whenever
gem install winrm
gem install webrick
gem install thor
gem install tty-prompt
gem install tty-table
gem install tty-spinner
gem install httparty
gem install rest-client
gem install typhoeus
gem install concurrent-ruby
gem install celluloid
gem install thread_safe
gem install rspec
gem install factory_bot
gem install faker
gem install minitest
gem install watir
gem install selenium-webdriver
gem install capybara
gem install rubyzip
gem install tar
gem install benchmark-ips
gem install memory_profiler
gem install fastimage
gem install google-apis-drive_v3
gem install optimist
exit
