#!/bin/bash
# Script Name: alsd1.sh
# ID: SCR-ID-20260412153439-BR4Z11R02R
# Assigned with:
# Created by: Tyler Jensen
# Email: tylerjensen5@yahoo.com
# Alias Call: alsd1

# actd - Active Directory Alias Manager (CSV + logs)

CONFIG_DIR="/mnt/c/scr/bash/alsd/logs"
CONFIG_FILE="$CONFIG_DIR/aliases.csv"
ALIAS_FILE="$HOME/.actd_aliases"

usage() {
    echo "Usage:"
    echo "  actd -a <alias_name> <directory>   Add new alias"
    echo "  actd -e <alias_name> <directory>   Edit existing alias"
    echo "  actd -d <alias_name>               Delete alias"
    echo "  actd -l                            List all aliases"
    exit 1
}

mkdir -p "$CONFIG_DIR"
touch "$CONFIG_FILE"

# Rebuild alias file from CSV
rebuild_alias_file() {
    echo "# Generated by actd" > "$ALIAS_FILE"
    while IFS=, read -r name dir; do
        [ -n "$name" ] && [ -n "$dir" ] && echo "alias $name='cd $dir'" >> "$ALIAS_FILE"
    done < "$CONFIG_FILE"
}

add_alias() {
    local name=$1
    local dir=$2
    if grep -q "^$name," "$CONFIG_FILE"; then
        echo "Alias '$name' already exists. Use -e to edit."
        exit 1
    fi
    echo "$name,$dir" >> "$CONFIG_FILE"
    rebuild_alias_file
    echo "Added alias: $name -> $dir"
}

edit_alias() {
    local name=$1
    local dir=$2
    if ! grep -q "^$name," "$CONFIG_FILE"; then
        echo "Alias '$name' does not exist. Use -a to add."
        exit 1
    fi
    # Replace existing entry
    sed -i "s|^$name,.*|$name,$dir|" "$CONFIG_FILE"
    rebuild_alias_file
    echo "Updated alias: $name -> $dir"
}

delete_alias() {
    local name=$1
    if ! grep -q "^$name," "$CONFIG_FILE"; then
        echo "Alias '$name' does not exist."
        exit 1
    fi
    sed -i "/^$name,/d" "$CONFIG_FILE"
    rebuild_alias_file
    echo "Deleted alias: $name"
}

list_aliases() {
    echo "Current directory aliases:"
    column -t -s, "$CONFIG_FILE" || echo "None yet."
}

# Parse args
case "$1" in
    -a) [ $# -eq 3 ] || usage; add_alias "$2" "$3" ;;
    -e) [ $# -eq 3 ] || usage; edit_alias "$2" "$3" ;;
    -d) [ $# -eq 2 ] || usage; delete_alias "$2" ;;
    -l) list_aliases ;;
    *) usage ;;
esac
